sfmdevdb:
    image: rajatvij/sfm-ui-db
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
sfmdevapp:
    image: rajatvij/sfm-ui:dev
    ports:
        - "8080:80"
    links:
        - sfmdevdb:db
    volumes:
        - ~/github/sfm:/opt/sfm-ui
    environment:
        - SFM_DEBUG=True
