sfmdevrabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmdevdb:
    image: gwul/sfm-ui-db
    environment:
        - POSTGRES_PASSWORD=gherD42#dl5
sfmdevapp:
    image: gwul/sfm-ui:dev
    ports:
        - "8080:80"
    links:
        - sfmdevdb:db
        - sfmdevrabbit:mq
    volumes:
        - ~/sfm-ui:/opt/sfm-ui
    environment:
        - SFM_DEBUG=True
